# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
any_nonpos <- function(x) {
    .Call('_PissoortThesis_any_nonpos', PACKAGE = 'PissoortThesis', x)
}

#' @export
cpp_gev_loglik <- function(x, data) {
    .Call('_PissoortThesis_cpp_gev_loglik', PACKAGE = 'PissoortThesis', x, data)
}

#' @export
gev_logpost <- function(x, data) {
    .Call('_PissoortThesis_gev_logpost', PACKAGE = 'PissoortThesis', x, data)
}

#' @export
gibbs_statioCpp <- function(start, data, iter, propsd, verbose) {
    .Call('_PissoortThesis_gibbs_statioCpp', PACKAGE = 'PissoortThesis', start, data, iter, propsd, verbose)
}

