# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

normal_gibbs <- function(data, mu0, t20, nu0, s20, burnin = 1000L, iter = 1000L, chains = 1L) {
    .Call('_PissoortThesis_normal_gibbs', PACKAGE = 'PissoortThesis', data, mu0, t20, nu0, s20, burnin, iter, chains)
}

any_nonpos <- function(x) {
    .Call('_PissoortThesis_any_nonpos', PACKAGE = 'PissoortThesis', x)
}

cpp_gev_loglik <- function(x, data) {
    .Call('_PissoortThesis_cpp_gev_loglik', PACKAGE = 'PissoortThesis', x, data)
}

gev_logpost <- function(x, data) {
    .Call('_PissoortThesis_gev_logpost', PACKAGE = 'PissoortThesis', x, data)
}

gibbs_statioCpp <- function(start, data, iter, propsd, verbose) {
    .Call('_PissoortThesis_gibbs_statioCpp', PACKAGE = 'PissoortThesis', start, data, iter, propsd, verbose)
}

f_gibbsC <- function(y, S, mu_0, tau2_0, sigma2_0, nu_0) {
    .Call('_PissoortThesis_f_gibbsC', PACKAGE = 'PissoortThesis', y, S, mu_0, tau2_0, sigma2_0, nu_0)
}

